title: Alvise Memo

source: src
destination: dst

timezone: America/San_Francisco

encoding: utf-8

description: >- # this means to ignore newlines until "baseurl:"
  My personal website to host and share some of my projects.

baseurl: ""
url: ""

#twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed